version: '3'

services:
  backend:
    image: msolomodenko/aws-loader-backend
    ports: 
      - 5123:5000

  frontend:
    image: msolomodenko/aws-loader-frontend
    ports: 
      - 5312:8080
      
   
