name: backend-pipeline

on:
  push:
    branches:
      - master
env:
 working-directory-backend: ./backend
 working-directory-frontend: ./frontend
 
jobs:    
  test:
    runs-on: ubuntu-latest
    steps:          
      - name: git clone
        uses: actions/checkout@v2        
      
     # - name: linter
        #working-directory: ${{env.working-directory-backend}}
        #run: |
         #go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2
         #golangci-lint run -v
         
      - name: tests
        working-directory: ${{env.working-directory-backend}}
        run: |
         go test ./...
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3        
      
      - name: build
        run: |
         docker build -t aws-education-file-loader-backend backend/
         docker build -t aws-education-file-loader-frontend frontend/
      
      - name: dockerhub setup
        run: |
         echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
         docker tag aws-education-file-loader-backend ${{secrets.DOCKER_USERNAME}}/aws-loader-backend
         docker tag aws-education-file-loader-frontend ${{secrets.DOCKER_USERNAME}}/aws-loader-frontend

      - name: push containers
        run: |          
          docker push ${{secrets.DOCKER_USERNAME}}/aws-loader-backend
          docker push ${{secrets.DOCKER_USERNAME}}/aws-loader-frontend
         
      - name: update dockerrun.json
        run: |
         sudo apt-get install jq
         jq '.AWSEBDockerrunVersion =  ${{ github.run_id }}' Dockerrun.aws.json > tmp.$$.json && mv tmp.$$.json Dockerrun.aws.json 
         
      - name: generate deployment package
        run: zip deploy.zip Dockerrun.aws.json

      - name: deploy to AWS
        uses: einaregilsson/beanstalk-deploy@v20
        with:

          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}

          application_name: file-loader
          environment_name: Fileloader-env

          region: "us-east-1"
          deployment_package: deploy.zip
          version_label: ${{ github.run_id }}
